version: "3.8"
services:
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nodeapp:
    build: .
    container_name: nodeapp_container
    ports:
      - "5100:5100"
    depends_on:
      - mongo

volumes:
  mongodb_data:
